language: python
python:
- "3.9"
before_script:
  - python -m nltk.downloader stopwords
  - python -m nltk.downloader vader_lexicon
install: "pip install -r requirements.txt"
script:
- python -m pytest