name: Restrict Merging to Main

on:
  pull_request:
    branches:
      - main

jobs:
  restrict-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [ "${{ github.base_ref }}" != "main" ] || [ "${{ github.head_ref }}" != "dev" ]; then
            echo "Only pull requests from dev to main are allowed."
            exit 1
          fi
